### ISSUE TITLE
Tests fail to build with clang-8

### ISSUE THREAD

**Issue by yurivict** [fizyr/estd#1] opened 2019-05-17 18:40 UTC
I'm getting these errors on FreeBSD 12.0:

```
/iterator.cpp.o -c /usr/ports/devel/estd/work/estd-0.3.1/test/traits/iterator.cpp
In file included from /usr/ports/devel/estd/work/estd-0.3.1/test/traits/iterator.cpp:29:
In file included from /usr/ports/devel/estd/work/estd-0.3.1/include/estd/traits/iterator.hpp:30:
/usr/include/c++/v1/iterator:988:32: error: incomplete type 'std::__1::char_traits<char>' named in nested name specifier
                      typename _Traits::off_type, _CharT*,
                               ^~~~~~~~~
/usr/include/c++/v1/iterator:446:77: note: in instantiation of template class 'std::__1::istreambuf_iterator<char, std::__1::char_traits<char> >' requested here
    template <class _Up> static char __test(typename std::__void_t<typename _Up::iterator_category>::type* = 0,
                                                                            ^
/usr/include/c++/v1/iterator:453:38: note: while substituting explicitly-specified template arguments into function template '__test' 
    static const bool value = sizeof(__test<_Tp>(0,0,0,0,0)) == 1;
                                     ^
/usr/include/c++/v1/iterator:499:32: note: in instantiation of template class 'std::__1::__has_iterator_typedefs<std::__1::istreambuf_iterator<char, std::__1::char_traits<char> > >' requested here
    : __iterator_traits<_Iter, __has_iterator_typedefs<_Iter>::value> {};
                               ^
/usr/ports/devel/estd/work/estd-0.3.1/include/estd/traits/iterator.hpp:69:60: note: in instantiation of template class 'std::__1::iterator_traits<std::__1::istreambuf_iterator<char, std::__1::char_traits<char> > >' requested here
                using type = typename minimal_iterator_tag<typename std::iterator_traits<T>::iterator_category...>::type;
                                                                         ^
/usr/ports/devel/estd/work/estd-0.3.1/include/estd/traits/iterator.hpp:99:33: note: in instantiation of template class 'estd::detail::minimal_iterator_category<std::__1::istreambuf_iterator<char, std::__1::char_traits<char> > >' requested here
template<typename ...Iterators> using minimal_iterator_category = typename detail::minimal_iterator_category<Iterators...>::type;
                                ^
/usr/ports/devel/estd/work/estd-0.3.1/test/traits/iterator.cpp:86:63: note: in instantiation of template type alias 'minimal_iterator_category' requested here
static_assert(std::is_same_v<std::input_iterator_tag,         minimal_iterator_category<std::istreambuf_iterator<char>>>);
                                                              ^
/usr/include/c++/v1/iosfwd:107:19: note: forward declaration of 'std::__1::char_traits<char>'
template<> struct char_traits<char>;
                  ^
In file included from /usr/ports/devel/estd/work/estd-0.3.1/test/traits/iterator.cpp:29:
In file included from /usr/ports/devel/estd/work/estd-0.3.1/include/estd/traits/iterator.hpp:30:
/usr/include/c++/v1/iterator:994:22: error: incomplete type 'std::__1::char_traits<char>' named in nested name specifier
    typedef typename _Traits::int_type      int_type;
                     ^~~~~~~~~
/usr/include/c++/v1/iosfwd:107:19: note: forward declaration of 'std::__1::char_traits<char>'
template<> struct char_traits<char>;
                  ^
In file included from /usr/ports/devel/estd/work/estd-0.3.1/test/traits/iterator.cpp:29:
/usr/ports/devel/estd/work/estd-0.3.1/include/estd/traits/iterator.hpp:69:80: error: no type named 'iterator_category' in 'std::__1::iterator_traits<std::__1::istreambuf_iterator<char, std::__1::char_traits<char> > >'
                using type = typename minimal_iterator_tag<typename std::iterator_traits<T>::iterator_category...>::type;
                                                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~
/usr/ports/devel/estd/work/estd-0.3.1/include/estd/traits/iterator.hpp:99:33: note: in instantiation of template class 'estd::detail::minimal_iterator_category<std::__1::istreambuf_iterator<char, std::__1::char_traits<char> > >' requested here
template<typename ...Iterators> using minimal_iterator_category = typename detail::minimal_iterator_category<Iterators...>::type;
                                ^
/usr/ports/devel/estd/work/estd-0.3.1/test/traits/iterator.cpp:86:63: note: in instantiation of template type alias 'minimal_iterator_category' requested here
static_assert(std::is_same_v<std::input_iterator_tag,         minimal_iterator_category<std::istreambuf_iterator<char>>>);
                                                              ^
/usr/ports/devel/estd/work/estd-0.3.1/test/traits/iterator.cpp:105:1: error: static_assert failed due to requirement 'std::is_same_v<std::__1::input_iterator_tag, int>'
static_assert(std::is_same_v<std::input_iterator_tag,         minimal_iterator_category<std::tuple<std::istreambuf_iterator<char>>>>);
^             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/ports/devel/estd/work/estd-0.3.1/test/traits/iterator.cpp:29:
/usr/ports/devel/estd/work/estd-0.3.1/include/estd/traits/iterator.hpp:113:103: error: no type named 'iterator_category' in 'std::__1::iterator_traits<std::__1::istreambuf_iterator<char, std::__1::char_traits<char> > >'
constexpr bool is_iterator_atleast = is_iterator_tag_atleast<typename std::iterator_traits<Iterator>::iterator_category, MinTag>;
                                                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~
/usr/ports/devel/estd/work/estd-0.3.1/test/traits/iterator.cpp:157:15: note: in instantiation of variable template specialization 'estd::is_iterator_atleast<std::__1::istreambuf_iterator<char, std::__1::char_traits<char> >, std::__1::input_iterator_tag>' requested here
static_assert(is_iterator_atleast<std::istreambuf_iterator<char>, std::input_iterator_tag>);
              ^
/usr/ports/devel/estd/work/estd-0.3.1/test/traits/iterator.cpp:157:15: error: static_assert expression is not an integral constant expression
static_assert(is_iterator_atleast<std::istreambuf_iterator<char>, std::input_iterator_tag>);
              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/ports/devel/estd/work/estd-0.3.1/test/traits/iterator.cpp:29:
/usr/ports/devel/estd/work/estd-0.3.1/include/estd/traits/iterator.hpp:113:103: error: no type named 'iterator_category' in 'std::__1::iterator_traits<std::__1::istreambuf_iterator<char, std::__1::char_traits<char> > >'
constexpr bool is_iterator_atleast = is_iterator_tag_atleast<typename std::iterator_traits<Iterator>::iterator_category, MinTag>;
                                                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~
/usr/ports/devel/estd/work/estd-0.3.1/test/traits/iterator.cpp:158:15: note: in instantiation of variable template specialization 'estd::is_iterator_atleast<std::__1::istreambuf_iterator<char, std::__1::char_traits<char> >, std::__1::output_iterator_tag>' requested here
static_assert(is_iterator_atleast<std::istreambuf_iterator<char>, std::output_iterator_tag>);
              ^
/usr/ports/devel/estd/work/estd-0.3.1/test/traits/iterator.cpp:158:15: error: static_assert expression is not an integral constant expression
static_assert(is_iterator_atleast<std::istreambuf_iterator<char>, std::output_iterator_tag>);
              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/ports/devel/estd/work/estd-0.3.1/test/traits/iterator.cpp:29:
/usr/ports/devel/estd/work/estd-0.3.1/include/estd/traits/iterator.hpp:113:103: error: no type named 'iterator_category' in 'std::__1::iterator_traits<std::__1::istreambuf_iterator<char, std::__1::char_traits<char> > >'
constexpr bool is_iterator_atleast = is_iterator_tag_atleast<typename std::iterator_traits<Iterator>::iterator_category, MinTag>;
                                                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~
/usr/ports/devel/estd/work/estd-0.3.1/test/traits/iterator.cpp:159:15: note: in instantiation of variable template specialization 'estd::is_iterator_atleast<std::__1::istreambuf_iterator<char, std::__1::char_traits<char> >, std::__1::forward_iterator_tag>' requested here
static_assert(is_iterator_atleast<std::istreambuf_iterator<char>, std::forward_iterator_tag>       == false);
              ^
/usr/ports/devel/estd/work/estd-0.3.1/test/traits/iterator.cpp:159:15: error: static_assert expression is not an integral constant expression
static_assert(is_iterator_atleast<std::istreambuf_iterator<char>, std::forward_iterator_tag>       == false);
              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/ports/devel/estd/work/estd-0.3.1/test/traits/iterator.cpp:29:
/usr/ports/devel/estd/work/estd-0.3.1/include/estd/traits/iterator.hpp:113:103: error: no type named 'iterator_category' in 'std::__1::iterator_traits<std::__1::istreambuf_iterator<char, std::__1::char_traits<char> > >'
constexpr bool is_iterator_atleast = is_iterator_tag_atleast<typename std::iterator_traits<Iterator>::iterator_category, MinTag>;
                                                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~
/usr/ports/devel/estd/work/estd-0.3.1/test/traits/iterator.cpp:160:15: note: in instantiation of variable template specialization 'estd::is_iterator_atleast<std::__1::istreambuf_iterator<char, std::__1::char_traits<char> >, std::__1::bidirectional_iterator_tag>' requested here
static_assert(is_iterator_atleast<std::istreambuf_iterator<char>, std::bidirectional_iterator_tag> == false);
              ^
/usr/ports/devel/estd/work/estd-0.3.1/test/traits/iterator.cpp:160:15: error: static_assert expression is not an integral constant expression
static_assert(is_iterator_atleast<std::istreambuf_iterator<char>, std::bidirectional_iterator_tag> == false);
              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/ports/devel/estd/work/estd-0.3.1/test/traits/iterator.cpp:29:
/usr/ports/devel/estd/work/estd-0.3.1/include/estd/traits/iterator.hpp:113:103: error: no type named 'iterator_category' in 'std::__1::iterator_traits<std::__1::istreambuf_iterator<char, std::__1::char_traits<char> > >'
constexpr bool is_iterator_atleast = is_iterator_tag_atleast<typename std::iterator_traits<Iterator>::iterator_category, MinTag>;
                                                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~
/usr/ports/devel/estd/work/estd-0.3.1/test/traits/iterator.cpp:161:15: note: in instantiation of variable template specialization 'estd::is_iterator_atleast<std::__1::istreambuf_iterator<char, std::__1::char_traits<char> >, std::__1::random_access_iterator_tag>' requested here
static_assert(is_iterator_atleast<std::istreambuf_iterator<char>, std::random_access_iterator_tag> == false);
              ^
/usr/ports/devel/estd/work/estd-0.3.1/test/traits/iterator.cpp:161:15: error: static_assert expression is not an integral constant expression
static_assert(is_iterator_atleast<std::istreambuf_iterator<char>, std::random_access_iterator_tag> == false);
              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
14 errors generated.
```

**Comment by de-vri-es** [comment] 2019-05-17 20:05
hmm, on Arch Linux with clang 8.0.0 the test compile fine. It seems to be an triggered with libc++ (on Arch, clang still uses libstdc++). I'm not sure yet if we're doing something wrong or if it's an issue with `libc++`.

**Comment by de-vri-es** [comment] 2019-05-17 20:39
It's caused by `std::isteambuf_iterator` using on `std::char_traits<T>` by default, but `<iterator>` not including `<string>`. Might make sense I suppose, since you could also pass in custom traits instead of `std::char_traits<T>`.

I think it's fixed by 9800de35ca8e0441c7fb3ea6061bdbece33b0cbc. The test now manually includes `<string>`. Could you test commit to see if it is indeed fixed for you?

**Comment by yurivict** [comment] 2019-05-17 23:31
Now tests succeed, thanks!

**Comment by de-vri-es** [comment] 2019-05-18 13:43
Good to hear. New release pushed =]

**Closed by de-vri-es** 2019-05-18 13:43 UTC
